### ISSUE TITLE
Link is expired in docs/qdrant/v1.0.x/search.md file

### ISSUE THREAD

**Issue by tusharxoxoxo** [qdrant/docs#61]
![Screenshot 2023-03-13 at 16 36 02](https://user-images.githubusercontent.com/79051850/224684569-11854330-1c36-4533-aa7d-7173c26dac7f.jpg)
![Screenshot 2023-03-13 at 16 36 12](https://user-images.githubusercontent.com/79051850/224684586-53a1f001-5870-4acb-b29d-04d367c9c76b.jpg)

## Steps to Reproduce

1. While I was reading through the documentation, I found that these links were not working or expired, I have attached their screenshots for clarity. 
2.
3.
4.

**Comment by joein** [comment]
@tusharxoxoxo it is actually not an issue

As you can see on https://qdrant.tech/documentation/search/ , the images are rendered properly.

Our website content is stored in at least two repositories:
 
[docs](https://github.com/qdrant/docs)
and 
[landing_page](https://github.com/qdrant/landing_page)

Which are being merged during deployment.

The images you are looking for can be found [here](https://github.com/qdrant/landing_page/tree/master/qdrant-landing/static/docs).

And since the paths in `.md` are relative, they are handled correctly later.

**Comment by tusharxoxoxo** [comment]
Okay, thank you @joein for clearing up my doubt. So I am closing the issue
